{
  lib,
  buildPythonPackage,
  fetchFromGitHub,

  # build-system
  setuptools,

  # dependencies
  numpy,
  ply,
  prettytable,
}:

# A backport, not a package of ours.  nixpkgs gained pycifrw between 26.05 and
# 26.11, and ../aiida-core needs it for the `atomic_tools` extra -- which is not
# optional here, because nativeCheckInputs ends with optional-dependencies.all
# and ../aiida-cp2k declares `aiida_core[atomic_tools]` as a runtime dependency.
# Without it the 26.05 leg of `just ci-matrix` does not reach a build at all:
#
#     error: evaluation aborted with the following error message:
#     'lib.customisation.callPackageWith: Function called without required
#      argument "pycifrw" at pkgs/aiida-core/default.nix:47'
#
# ../../overlays/default.nix takes nixpkgs' when the channel has one, so on
# 26.11 this file is dead weight.  Kept deliberately close to nixpkgs'
# pkgs/development/python-modules/pycifrw rather than restyled, so the two can
# be diffed, and so deleting it is the obvious move once 26.05 leaves the
# matrix in .github/workflows/build.yml.
buildPythonPackage rec {
  pname = "pycifrw";
  version = "5.0.1";
  pyproject = true;

  src = fetchFromGitHub {
    owner = "jamesrhester";
    repo = "pycifrw";
    tag = "v${version}";
    hash = "sha256-b55+Vb2H/ADl586o5ch0X4HurwsbbgDg5XS5/8QhFZM=";
  };

  # The two CIF grammars are generated by ply's yacc at build time rather than
  # committed, so an unbuilt tree imports but parses nothing.
  preBuild = ''
    make -C src Parsers
  '';

  build-system = [ setuptools ];

  dependencies = [
    numpy
    prettytable
    ply
  ];

  # nixpkgs' judgement, carried over unexamined: the suite wants CIF dictionaries
  # (dics/DDLm/cif_mag.dic and friends) that the repository does not ship.  This
  # is the one place here where `doCheck = false` is taken on trust rather than
  # from a run -- see the sdist-has-no-tests note in ../../AGENTS.md for why that
  # is normally worth a second look.
  doCheck = false;

  pythonImportsCheck = [ "CifFile" ];

  meta = {
    description = "Python library for reading and writing CIF files";
    homepage = "https://github.com/jamesrhester/pycifrw";
    changelog = "https://github.com/jamesrhester/pycifrw/releases/tag/v${version}";
    license = lib.licenses.psfl;
    maintainers = with lib.maintainers; [ berquist ];
  };
}
